global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'deepfake-api'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - deepfake-detection
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: deepfake-api
        action: keep
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        regex: 8000
        action: keep
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: app
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['deepfake-postgres:5432']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['deepfake-redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
      - targets: ['deepfake-nginx:80']
    metrics_path: /nginx_status
    scrape_interval: 30s 